name: Compile Latex and put pdfs in asset-pdf branch

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build_pdf.yml"
      - "**.tex"
      - "**.sty"
      - "**.bib"
      - "**.cls"

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: TeXLive Action
        # You may pin to the exact commit or the version.
        # uses: repaction/texlive@6713a805bd9bab56c4777f06c62b10de1c787750
        uses: repaction/texlive@mini-v2
        with:
          # The LaTeX file to be compiled.
          tex_files: Analysis-3.tex
