name: Compile Latex and push to github pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**.yml"
      - ".github/**.md"
      - "**.tex"
      - "**.pdf_tex"
      - "**.sty"
      - "**.bib"
      - "**.cls"
      - "**.pdf"
      - "**.sh"
      - "latexmkrc"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Cache the pdfs
        id: cache-ra-3
        uses: actions/cache@v3
        with:
          path: pdfs
          key: analysis-3-${{ hashFiles('style.sty') }}-${{ hashFiles('**/*tex') }}-${{ hashFiles('**/*pdf_tex') }}-${{ hashFiles('**/*pdf') }}-${{ hashFiles('./latexmkrc') }}
          restore-keys: |
            analysis-3-${{ hashFiles('style.sty') }}-
            analysis-3-${{ hashFiles('style.sty') }}-${{ hashFiles('**/*tex') }}-

      - name: Cache the pgfplots
        id: cache-pgfplots
        uses: actions/cache@v3
        with:
          path: pgfplot_figures
          key: pgfplot-figures-${{ hashFiles('pgfplots/**/*tex') }}
          restore-keys: |
            pgfplot-figures-

      - if: ${{ steps.cache-pgfplots.outputs.cache-hit == 'true' }}
        name: Retrive pgfplot_figures
        run: bash ./github/scripts/_pgf_retrive.sh

      - if: ${{ steps.cache-pgfplots.outputs.cache-hit != 'true' }}
        name: Build pgfplots
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./pgfplots
          root_file: "*.tex"
          glob_root_file: true
          latexmk_shell_escape: true
          post_compile: bash ../github/scripts/_pgf_cache.sh

      - if: ${{ steps.cache-ra-3.outputs.cache-hit != 'true' }}
        name: Compile the Aanlysis-3.pdf
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: .
          root_file: ./Analysis-3.tex
          latexmk_shell_escape: true

      - if: ${{ steps.cache-ra-3.outputs.cache-hit != 'true' }}
        name: Compile all the subfiles
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./lectures
          root_file: "*.tex"
          glob_root_file: true
          latexmk_shell_escape: true

      - if: ${{ steps.cache-ra-3.outputs.cache-hit != 'true' }}
        name: Put pdfs in a single directory
        run: bash ./.github/scripts/_pdf.sh

      - name: Create _site
        run: bash ./.github/scripts/_site.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_pdf
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
