name: Compile Latex and push to github pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**.yml"
      - ".github/**.md"
      - "**.tex"
      - "**.pdf_tex"
      - "**.sty"
      - "**.bib"
      - "**.cls"
      - "**.pdf"
      - "**.sh"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Cache the pdfs
        id: cache-ra-3
        uses: actions/cache@v3
        with:
          path: pdfs
          key: analysis-3-${{ hashFiles('style.sty') }}-${{ hashFiles('**/*tex') }}-${{ hashFiles('**/*pdf_tex') }}-${{ hashFiles('**/*pdf') }}
          restore-keys: |
            analysis-3-${{ hashFiles('style.sty') }}-
            analysis-3-${{ hashFiles('style.sty') }}-${{ hashFiles('**/*tex') }}-

      - if: ${{ steps.cache-ra-3.outputs.cache-hit != 'true' }}
        name: Compile pdf
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: .
          root_file: ./Analysis-3.tex

      - if: ${{ steps.cache-ra-3.outputs.cache-hit != 'true' }}
        name: Compile all pdfs
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./lectures
          root_file: "*.tex"
          glob_root_file: true
          compiler: pdflatex

      - if: ${{ steps.cache-ra-3.outputs.cache-hit != 'true' }}
        name: Put pdfs in a single directory
        run: bash _pdf.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_pdf
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
